apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: cqlsh
  name: cqlsh
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: cqlsh
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: cqlsh
    spec:
      containers:
      - args:
        - bash
        image: docker.io/scraly/cqlsh:latest
        imagePullPolicy: Always
        name: cqlsh
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
